package leltar;

import java.awt.event.KeyEvent;

/**
 * Leltár program
 * @author Tóth József
 */
public class Ablak extends javax.swing.JFrame {

    DB ab;
    
    public Ablak() {
        initComponents();
        ab = new DB();
        ab.termek_be(tblTermek_1, cbxTerem_3);
        ab.eszkozok_be(tblEszkoz_2, cbxEszkoz_3);
        ab.leltar_be(tblLeltar_3);
    }
        
    private void termek_tablabol() {
        int i = tblTermek_1.getSelectedRow();
        txtTerem_1.setText(tblTermek_1.getValueAt(i, 1).toString());
        Object e = tblTermek_1.getValueAt(i, 2);
        if (e != null)
            txtFelh_1.setText(e.toString());
        else 
            txtFelh_1.setText("");
    }

    private void eszkozok_tablabol() {
        int i = tblEszkoz_2.getSelectedRow();
        txtEszkoz_2.setText(tblEszkoz_2.getValueAt(i, 1).toString());
        Object e = tblEszkoz_2.getValueAt(i, 2);
        if (e != null)
            txtEv_2.setText(e.toString());
        else 
            txtEv_2.setText("");
    }

    private void leltar_tablabol() {
        int i = tblLeltar_3.getSelectedRow();
        String terem = tblLeltar_3.getValueAt(i, 1).toString();
        String eszkoz = tblLeltar_3.getValueAt(i, 2).toString();       
        cbxTerem_3.setSelectedItem(terem);
        cbxEszkoz_3.setSelectedItem(eszkoz);
        Object a = tblLeltar_3.getValueAt(i, 3);
        if (a != null) 
            txtAdatok_3.setText(a.toString());
        else
            txtAdatok_3.setText("");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTermek_1 = new javax.swing.JTable();
        txtTerem_1 = new javax.swing.JTextField();
        txtFelh_1 = new javax.swing.JTextField();
        btnHozzaad_1 = new javax.swing.JButton();
        btnModosit_1 = new javax.swing.JButton();
        btntorol_1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEszkoz_2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEszkoz_2 = new javax.swing.JTextField();
        txtEv_2 = new javax.swing.JTextField();
        btnHozzaad_2 = new javax.swing.JButton();
        btnModosit_2 = new javax.swing.JButton();
        btntorol_2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLeltar_3 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbxTerem_3 = new javax.swing.JComboBox<>();
        cbxEszkoz_3 = new javax.swing.JComboBox<>();
        txtAdatok_3 = new javax.swing.JTextField();
        btnHozzaad_3 = new javax.swing.JButton();
        btnModosit_3 = new javax.swing.JButton();
        btntorol_3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eszköznyilvántartás");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Teremszám:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Felhasználás:");

        tblTermek_1.setAutoCreateRowSorter(true);
        tblTermek_1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblTermek_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Teremszám", "Felhasználás"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTermek_1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblTermek_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTermek_1MouseClicked(evt);
            }
        });
        tblTermek_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblTermek_1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblTermek_1);
        if (tblTermek_1.getColumnModel().getColumnCount() > 0) {
            tblTermek_1.getColumnModel().getColumn(0).setMinWidth(0);
            tblTermek_1.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblTermek_1.getColumnModel().getColumn(0).setMaxWidth(0);
            tblTermek_1.getColumnModel().getColumn(1).setPreferredWidth(60);
            tblTermek_1.getColumnModel().getColumn(2).setPreferredWidth(240);
        }

        txtTerem_1.setText(" ");

        btnHozzaad_1.setMnemonic('h');
        btnHozzaad_1.setText("Hozzáad");
        btnHozzaad_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHozzaad_1ActionPerformed(evt);
            }
        });

        btnModosit_1.setMnemonic('m');
        btnModosit_1.setText("Módosít");
        btnModosit_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModosit_1ActionPerformed(evt);
            }
        });

        btntorol_1.setMnemonic('t');
        btntorol_1.setText("Töröl");
        btntorol_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntorol_1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTerem_1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtFelh_1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnHozzaad_1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 15, Short.MAX_VALUE)
                        .addComponent(btnModosit_1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 16, Short.MAX_VALUE)
                        .addComponent(btntorol_1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHozzaad_1, btnModosit_1, btntorol_1});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtTerem_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtFelh_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModosit_1)
                            .addComponent(btnHozzaad_1)
                            .addComponent(btntorol_1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Termek", jPanel1);

        tblEszkoz_2.setAutoCreateRowSorter(true);
        tblEszkoz_2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Eszköz neve", "Beszerzés éve"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEszkoz_2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblEszkoz_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEszkoz_2MouseClicked(evt);
            }
        });
        tblEszkoz_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblEszkoz_2KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblEszkoz_2);
        if (tblEszkoz_2.getColumnModel().getColumnCount() > 0) {
            tblEszkoz_2.getColumnModel().getColumn(0).setMinWidth(0);
            tblEszkoz_2.getColumnModel().getColumn(0).setMaxWidth(0);
            tblEszkoz_2.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblEszkoz_2.getColumnModel().getColumn(2).setPreferredWidth(80);
        }

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Eszköz neve:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Beszerzés éve:");

        txtEszkoz_2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtEv_2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnHozzaad_2.setMnemonic('h');
        btnHozzaad_2.setText("Hozzáad");
        btnHozzaad_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHozzaad_2ActionPerformed(evt);
            }
        });

        btnModosit_2.setMnemonic('m');
        btnModosit_2.setText("Módosít");
        btnModosit_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModosit_2ActionPerformed(evt);
            }
        });

        btntorol_2.setMnemonic('t');
        btntorol_2.setText("Töröl");
        btntorol_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntorol_2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEv_2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEszkoz_2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnHozzaad_2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(btnModosit_2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(btntorol_2, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtEszkoz_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtEv_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHozzaad_2)
                            .addComponent(btntorol_2)
                            .addComponent(btnModosit_2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Eszközök", jPanel2);

        tblLeltar_3.setAutoCreateRowSorter(true);
        tblLeltar_3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Terem", "Eszköz", "Adatok"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLeltar_3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblLeltar_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLeltar_3MouseClicked(evt);
            }
        });
        tblLeltar_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblLeltar_3KeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tblLeltar_3);
        if (tblLeltar_3.getColumnModel().getColumnCount() > 0) {
            tblLeltar_3.getColumnModel().getColumn(0).setMinWidth(0);
            tblLeltar_3.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblLeltar_3.getColumnModel().getColumn(0).setMaxWidth(0);
            tblLeltar_3.getColumnModel().getColumn(1).setPreferredWidth(40);
            tblLeltar_3.getColumnModel().getColumn(2).setPreferredWidth(250);
            tblLeltar_3.getColumnModel().getColumn(3).setPreferredWidth(250);
        }

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Terem:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Eszköz:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Adatok:");

        cbxTerem_3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cbxEszkoz_3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtAdatok_3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnHozzaad_3.setMnemonic('h');
        btnHozzaad_3.setText("Hozzáad");
        btnHozzaad_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHozzaad_3ActionPerformed(evt);
            }
        });

        btnModosit_3.setMnemonic('m');
        btnModosit_3.setText("Módosít");
        btnModosit_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModosit_3ActionPerformed(evt);
            }
        });

        btntorol_3.setMnemonic('t');
        btntorol_3.setText("Töröl");
        btntorol_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntorol_3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAdatok_3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxEszkoz_3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxTerem_3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnModosit_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHozzaad_3, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(btntorol_3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTerem_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btnHozzaad_3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxEszkoz_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(btnModosit_3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtAdatok_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntorol_3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Leltár", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblTermek_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTermek_1MouseClicked
        termek_tablabol();
    }//GEN-LAST:event_tblTermek_1MouseClicked

    private void tblTermek_1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblTermek_1KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_UP 
                || evt.getKeyCode() == KeyEvent.VK_DOWN
                || evt.getKeyCode() == KeyEvent.VK_PAGE_UP
                || evt.getKeyCode() == KeyEvent.VK_PAGE_DOWN)
            termek_tablabol();
    }//GEN-LAST:event_tblTermek_1KeyReleased

    private void tblEszkoz_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEszkoz_2MouseClicked
        eszkozok_tablabol();
    }//GEN-LAST:event_tblEszkoz_2MouseClicked

    private void tblLeltar_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLeltar_3MouseClicked
        leltar_tablabol();
    }//GEN-LAST:event_tblLeltar_3MouseClicked

    private void tblEszkoz_2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblEszkoz_2KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_UP 
                || evt.getKeyCode() == KeyEvent.VK_DOWN
                || evt.getKeyCode() == KeyEvent.VK_PAGE_UP
                || evt.getKeyCode() == KeyEvent.VK_PAGE_DOWN)
            eszkozok_tablabol();
    }//GEN-LAST:event_tblEszkoz_2KeyReleased

    private void tblLeltar_3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblLeltar_3KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_UP 
                || evt.getKeyCode() == KeyEvent.VK_DOWN
                || evt.getKeyCode() == KeyEvent.VK_PAGE_UP
                || evt.getKeyCode() == KeyEvent.VK_PAGE_DOWN)
            leltar_tablabol();
    }//GEN-LAST:event_tblLeltar_3KeyReleased

    private void btnHozzaad_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHozzaad_1ActionPerformed
        ab.terem_hozzaad(txtTerem_1.getText(),txtFelh_1.getText());
        ab.termek_be(tblTermek_1, cbxTerem_3);
    }//GEN-LAST:event_btnHozzaad_1ActionPerformed

    private void btnHozzaad_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHozzaad_2ActionPerformed
        ab.eszkoz_hozzaad(txtEszkoz_2.getText(),txtEv_2.getText());
        ab.eszkozok_be(tblEszkoz_2, cbxEszkoz_3);
    }//GEN-LAST:event_btnHozzaad_2ActionPerformed

    private void btnHozzaad_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHozzaad_3ActionPerformed
        ab.leltar_hozzaad(ab.get_teremid(cbxTerem_3.getSelectedItem().toString()),
                          ab.get_eszkozid(cbxEszkoz_3.getSelectedItem().toString()),
                          txtAdatok_3.getText());
        ab.leltar_be(tblLeltar_3);
    }//GEN-LAST:event_btnHozzaad_3ActionPerformed

    private void btnModosit_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModosit_1ActionPerformed
        int i = tblTermek_1.getSelectedRow();
        if (i == -1) return;
        ab.terem_modosit(Integer.parseInt(tblTermek_1.getValueAt(i, 0).toString()),
                         txtTerem_1.getText(), txtFelh_1.getText());
        ab.termek_be(tblTermek_1, cbxTerem_3);
    }//GEN-LAST:event_btnModosit_1ActionPerformed

    private void btnModosit_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModosit_2ActionPerformed
        int i = tblEszkoz_2.getSelectedRow();
        if (i == -1) return;
        ab.eszkoz_modosit(Integer.parseInt(tblEszkoz_2.getValueAt(i, 0).toString()),
                          txtEszkoz_2.getText(), txtEv_2.getText());
        ab.eszkozok_be(tblEszkoz_2, cbxEszkoz_3);
    }//GEN-LAST:event_btnModosit_2ActionPerformed

    private void btnModosit_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModosit_3ActionPerformed
        int i = tblLeltar_3.getSelectedRow();
        if (i == -1) return;
        ab.leltar_modosit(Integer.parseInt(tblLeltar_3.getValueAt(i, 0).toString()),
                ab.get_teremid(cbxTerem_3.getSelectedItem().toString()),
                ab.get_eszkozid(cbxEszkoz_3.getSelectedItem().toString()),
                txtAdatok_3.getText());
        ab.leltar_be(tblLeltar_3);
    }//GEN-LAST:event_btnModosit_3ActionPerformed

    private void btntorol_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntorol_1ActionPerformed
        int i = tblTermek_1.getSelectedRow();
        if (i == -1) return;
        ab.terem_torol(Integer.parseInt(tblTermek_1.getValueAt(i, 0).toString()));
        ab.termek_be(tblTermek_1, cbxTerem_3);
    }//GEN-LAST:event_btntorol_1ActionPerformed

    private void btntorol_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntorol_2ActionPerformed
        int i = tblEszkoz_2.getSelectedRow();
        if (i == -1) return;
        ab.eszkoz_torol(Integer.parseInt(tblEszkoz_2.getValueAt(i, 0).toString()));
        ab.eszkozok_be(tblEszkoz_2, cbxEszkoz_3);       
    }//GEN-LAST:event_btntorol_2ActionPerformed

    private void btntorol_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntorol_3ActionPerformed
        int i = tblLeltar_3.getSelectedRow();
        if (i == -1) return;
        ab.leltar_torol(Integer.parseInt(tblLeltar_3.getValueAt(i, 0).toString()));
        ab.leltar_be(tblLeltar_3);     
    }//GEN-LAST:event_btntorol_3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ablak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHozzaad_1;
    private javax.swing.JButton btnHozzaad_2;
    private javax.swing.JButton btnHozzaad_3;
    private javax.swing.JButton btnModosit_1;
    private javax.swing.JButton btnModosit_2;
    private javax.swing.JButton btnModosit_3;
    private javax.swing.JButton btntorol_1;
    private javax.swing.JButton btntorol_2;
    private javax.swing.JButton btntorol_3;
    private javax.swing.JComboBox<String> cbxEszkoz_3;
    private javax.swing.JComboBox<String> cbxTerem_3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblEszkoz_2;
    private javax.swing.JTable tblLeltar_3;
    private javax.swing.JTable tblTermek_1;
    private javax.swing.JTextField txtAdatok_3;
    private javax.swing.JTextField txtEszkoz_2;
    private javax.swing.JTextField txtEv_2;
    private javax.swing.JTextField txtFelh_1;
    private javax.swing.JTextField txtTerem_1;
    // End of variables declaration//GEN-END:variables
}
